# MySQL
# spring:
#   application:
#     name: auth-service
#   datasource:
#     url: ${DB_URL}
#     username: ${DB_USERNAME}
#     password: ${DB_PASSWORD}
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     open-in-view: false
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         format_sql: true
#         jdbc:
#           time_zone: UTC
#   jackson:
#     default-property-inclusion: non_null
#     serialization:
#       write-dates-as-timestamps: false

# server:
#   port: ${SERVER_PORT:8080}

# app:
#   jwt:
#     jwt-secret: ${JWT_SECRET}
#     access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
#     refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

# logging:
#   level:
#     org.springframework.security: INFO

# PostgreSQL
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: adse
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    jwt-secret: ${JWT_SECRET}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
